
---
version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
    pre_build:
        commands:
          - echo Installing linters...
          - pip install cfn-lint pycodestyle
          - echo Testing python code...
          - cd $CODEBUILD_SRC_DIR
          - pycodestyle  --ignore=E501 $(pwd)/application
          - echo "Starting build `date` in `pwd`"
          - echo testing SAM app template ...
          - cfn-lint ./rdsoperation/template.yaml
          - echo Check if the auth layer exists before build the app ...
          - aws lambda get-layer-version --layer-name api-authorization-layer --version-number 1 >> /dev/null
    build:
        commands:
          - cd $CODEBUILD_SRC_DIR
          - echo "Starting build `date` in `pwd`"
          - aws cloudformation package
            --s3-bucket=${BUILD_OUTPUT_BUCKET}
            --s3-prefix=${BUILD_OUTPUT_PREFIX}
            --template-file=application/template.yaml
            --output-template-file=application/packaged.yaml
    post_build:
        commands:
          - echo "build completed on `date`"
artifacts:
    base-directory: ./application
    files:
      - packaged.yaml