
---
version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
    build:
        commands:
          - cd $CODEBUILD_SRC_DIR
          - echo "Starting build `date` in `pwd`"
          - pwd
          #- cfn-lint --template application/template.yaml --regions $AWS_REGION
          #- aws cloudformation validate-template --template-body file://$(pwd)/aplication/template.yaml
          - aws cloudformation package
                --s3-bucket=${BUILD_OUTPUT_BUCKET}
                --s3-prefix=${BUILD_OUTPUT_PREFIX}
                --template-file=application/template.yaml
                --output-template-file=application/packaged.yaml
artifacts:
    base-directory: ./application
    files:
      - packaged.yaml