AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  os-cloud-cwusers
  //TODO description of the aplication

  Sample SAM Template for os-cloud-cwusers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CWUsers:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    #Todo place role
    Properties:
      CodeUri: ./lambda
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        CreateUser:
          Type: Api 
          Properties:
            Path: /cwuser
            Method: post
        ResetUserPassword:
          Type: Api 
          Properties:
            Path: /cwuser
            Method: put
        DeleteUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cwuser
            Method: delete

  

#TODO: Get api ids and add this schema to the generated apis
  #RequestValidator:
  #  Type: AWS::ApiGateway::Model
  #  Properties:
  #    ContentType: "application/json"
  #   Name: "CWUserApiValidator"
  #    Schema:
  #      $schema: "http://json-schema.org/draft-04/schema#"
  #      title: Application Json
  #      required:
  #        - token
  #        - username
  #      type: object
  #      properties:
  #        token:
  #          type: string
  #        username:
  #          type: string